Feature/update readme
Cobda/cobda-web pull request #10
Opened 2021-01-25 10:45 UTC by kimvcp

https://app.clubhouse.io/cobda/story/80/update-readme-md

## Why?

This PR is for updating the content in the `README.md` file.

## Changes

Added necessary topics.

## Screenshot(s)

**Before** 

<img width="761" alt="Screen Shot 2564-01-25 at 17 44 34" src="https://user-images.githubusercontent.com/32285706/105695724-fe0af080-5f34-11eb-9313-1a0e86a4fd1d.png">

**After**

<img width="758" alt="Screen Shot 2564-01-25 at 17 44 48" src="https://user-images.githubusercontent.com/32285706/105695754-06632b80-5f35-11eb-84d6-50a66c9865e6.png">

2021-01-25 15:07 UTC, LilBank requested changes

2021-01-25 15:07 UTC, LilBank commented on README.md
> +**Cobda** is a community-like e-commerce website for selling and buying streetwear stuff. Plus, it's accessible anywhere and anytime through the internet.
```suggestion
**Cobda** is a community-like e-commerce website for selling and buying streetwears. Plus, it's accessible through any online devices.
```

2021-01-25 15:07 UTC, LilBank commented on README.md
> +## Prerequisite
```suggestion
## Prerequisites
```

2021-01-25 15:07 UTC, LilBank commented on README.md
> +- `local environment variable` **Please ask project owner privately for the environment variables.**
```suggestion
- `.env` **Please ask project owner privately for the environment variables.**
```

2021-01-25 15:07 UTC, LilBank commented on README.md
> +You must download the following to be able to run.
I don't think this sentence is necessary this the title already has its own meaning.

2021-01-25 19:45 UTC, Raksani requested changes

2021-01-25 19:45 UTC, Raksani commented on README.md
> +**Cobda** is a community-like e-commerce website for selling and buying streetwears. Plus, it's accessible through any online devices.
Grammar check 👍🏻
```suggestion
**Cobda** is a streetwear e-commerce website where sellers and buyers meet each other with ease, driven by our desire to make community-like websites available to everyone in a friendly way. **Make certain** with a powerful AI function that automatically takes out inappropriate and irrelevant content to make sure your vibe goes as smoothly as possible. **Buy with confidence** by looking at product reviews and buyer's profile. This website runs perfectly on any online device. 
```

2021-01-26 07:59 UTC, LilBank commented on README.md
> +**Cobda** is a streetwear e-commerce website where sellers and buyers meet each other with ease, driven by our desire to make community-like websites available to everyone in a friendly way. **Make c
```suggestion
**Cobda** is a streetwear e-commerce website where sellers and buyers met with ease. With a community alike design, it's available for every genders and generations. **Make certain** with an autonomous feature that validate newly registered products at instant. Selling product is now faster than ever. **Buy with confidence** guaranteed by other customers. The review system builds up credits for the seller while giving confidence to the buyer vice versa. Finally, accessible through any devices with an internet connection 😎
```

2021-01-26 08:05 UTC, kimvcp commented on README.md
> +**Cobda** is a streetwear e-commerce website where sellers and buyers meet each other with ease, driven by our desire to make community-like websites available to everyone in a friendly way. **Make c
```suggestion
**Cobda** is a streetwear e-commerce website where sellers and buyers met with ease. With a community alike design, it's available for every gender and generation. **Make certain** with an autonomous feature that validates newly registered products at the instant. Selling product is now faster than ever. **Buy with confidence** guaranteed by other customers. The review system builds up credits for the seller while giving confidence to the buyer vice versa. Moreover, accessible through any devices with an internet connection 😎
```

2021-01-26 08:10 UTC, Kittinske15 approved these changes

2021-01-26 08:10 UTC, LilBank approved these changes

2021-01-30 13:24 UTC, merged