[ch85] As a user, I can see homepage structure explicitly
Cobda/cobda-web pull request #12
Opened 2021-01-25 16:55 UTC by LilBank

https://app.clubhouse.io/cobda/story/85/as-a-user-i-can-see-homepage-structure-explicitly

## Why?

This is an update for Home Screen to see each sections with grid implementation.

To describe the reason for creating this **PR**.

## Changes

- Add layout for home page.

## Screenshot(s)

### Desktop
![Screen Shot 2564-01-25 at 23 52 51](https://user-images.githubusercontent.com/32289827/105737521-a25a5a80-5f68-11eb-935b-5e8402697025.png)

### Mobile
![Screen Shot 2564-01-25 at 23 53 04](https://user-images.githubusercontent.com/32289827/105737532-a6867800-5f68-11eb-8b47-20d90a92398a.png)

2021-01-25 17:06 UTC, kimvcp requested changes

2021-01-25 17:06 UTC, kimvcp commented on src/components/HomeSection/index.tsx
> +}
Please add a newline (Resolve when fixed)
```suggestion
}

```

2021-01-25 17:06 UTC, kimvcp commented on src/screens/Home/index.tsx
> +import { useEffect } from 'react';
```suggestion
import React, { useEffect } from 'react';
```

They are from the same module. We should group them up

2021-01-25 17:06 UTC, kimvcp commented on src/scss/components/_home-section.scss
> +}
Newline needed (Resolve when fixed)

2021-01-25 17:06 UTC, kimvcp commented on src/scss/layouts/_layout-home.scss
> +}
Newline needed (Resolve when fixed)

2021-01-25 17:13 UTC, kimvcp commented on src/scss/components/_home-section.scss
> +    }
Please use two indents for the tab size.

```suggestion
  width: 100%;
  height: rem(200px);
  background-color: aquamarine;
  padding: rem(16px);
  box-sizing: border-box;

  @include respond-above('md') {
    padding: rem(24px);
    height: rem(320px);
  }

  @include respond-above('lg') {
    padding: rem(32px);
    height: rem(400px);
  }

  &--dark {
    background-color: blue;
  }

  &--light {
    background-color: blueviolet;
  }

  // TODO: For future implementation
  &__header {
  }

  &__title {
    margin: 0 0 rem(24px) 0;
  }

  &__description {
    margin: 0;
  }
```

2021-01-25 17:16 UTC, kimvcp commented on src/scss/layouts/_layout-home.scss
> +    }
This one also needs two indents for tab size

```suggestion
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: rem(32px) 1fr rem(48px);
  grid-template-areas:
    'header'
    'main'
    'footer';

  height: 100vh;

  @include respond-above('md') {
    grid-template-rows: rem(48px) 1fr rem(72px);
  }

  @include respond-above('lg') {
    grid-template-rows: rem(72px) 1fr rem(100px);
  }

  & > header {
    grid-area: header;
  }

  & > main {
    grid-area: main;

    padding: rem(24px) rem(16px);

    @include respond-above('md') {
      padding: 4.5%;
    }

    @include respond-above('lg') {
      padding: 5% 10%;
    }
  }

  & > footer {
    grid-area: footer;
  }
```

2021-01-25 17:16 UTC, kimvcp commented on src/scss/layouts/__layouts-dir.scss
> +@import './layout-home';
Newline needed (Resolve when fixed)
```suggestion
@import './layout-home';

```

2021-01-25 17:19 UTC, Kittinske15 approved these changes

2021-01-25 18:50 UTC, Raksani requested changes

2021-01-25 18:50 UTC, Raksani commented on src/scss/layouts/_layout-home.scss
> +
Does it need the extra space here?

2021-01-26 06:12 UTC, LilBank commented on src/scss/layouts/_layout-home.scss
> +
Sure, just for grid.

2021-01-26 07:13 UTC, kimvcp commented on src/scss/layouts/_layout-home.scss
> +  }
This one also needs 2 indents.

```suggestion
    @include respond-above('md') {
      padding: 4.5% 6%;
    }

    @include respond-above('lg') {
      padding: 5% 10%;
    }
  }
```

2021-01-26 07:15 UTC, Kittinske15 approved these changes

2021-01-26 07:21 UTC, kimvcp approved these changes

2021-01-26 07:23 UTC, merged