Feature/sign in screen
Cobda/cobda-web pull request #22
Opened 2021-02-10 18:29 UTC by Kittinske15

[STORY_LINK]

## Why?

To describe the reason for creating this **PR**.

## Changes

What are the changes. Explain them explicitly.

## Screenshot(s)

A screenshot **before** the implementation and **after** the implementation.

2021-02-10 19:49 UTC, LilBank approved these changes

2021-02-10 19:56 UTC, LilBank requested changes

2021-02-10 19:56 UTC, LilBank commented on src/styles/components/_sign-in-form.scss
> +  &__footer-item > p {
We can select all one level child by this
```suggestion
  &__footer-item > * {
```

2021-02-10 19:57 UTC, LilBank requested changes

2021-02-10 19:57 UTC, LilBank commented on src/styles/components/_sign-in-form.scss
> +  }
```suggestion
  &__footer-item {
    &:not(:last-child) {
      margin-bottom: rem(8px);
      
      & > * {
        margin-bottom: rem(4px);
      }
    }
  }
```

2021-02-11 07:03 UTC, kimvcp approved these changes

2021-02-11 07:05 UTC, LilBank approved these changes

2021-02-11 07:10 UTC, merged