[ch139][ch141] As a user, I can see category section and items
Cobda/cobda-web pull request #28
Opened 2021-02-20 18:18 UTC by LilBank

https://app.clubhouse.io/cobda/story/141/as-a-user-i-can-see-category-items
https://app.clubhouse.io/cobda/story/139/as-a-user-i-can-see-categories-section

## Why?

In home page, the categories section located under home search section.

## Changes

- Add category section
- Add category items

## Screenshot(s)

![Screen Shot 2564-02-21 at 01 17 43](https://user-images.githubusercontent.com/32289827/108604797-a9974b80-73e2-11eb-90ce-83e693b4abdf.png)

2021-02-20 18:46 UTC, kimvcp commented on src/components/HomeCategory/index.tsx
> +        caption={"HypeBeast"} />
🧐

```suggestion
      <HomeCategoryItem
        imagePath={'/images/yeezy-380.jpg'}
        alternate={'Adidas Yeezy 380 from Pexels by @ox-street-3848035'}
        caption={'Yeezys'}
      />
      <HomeCategoryItem
        imagePath={'/images/blue-nike-jordan.jpg'}
        alternate={'Nike Jordan from Pexels by @desertedinurban'}
        caption={'Jordans'}
      />
      <HomeCategoryItem
        imagePath={'/images/rolling-stone-shirt.jpg'}
        alternate={"One of the Author's vintage t-shirt collection"}
        caption={'Vintage'}
      />
      <HomeCategoryItem
        imagePath={'/images/nike-jordan-off-white.jpg'}
        alternate={'Nike Air Jordan X Off White from Pexels by @introspectivedsgn'}
        caption={'HypeBeast'}
      />
```

2021-02-20 18:49 UTC, kimvcp commented on src/components/PopularItemCarousel/index.tsx
> +import { CarouselProvider, Slider, Slide, ButtonBack, ButtonNext, DotGroup } from 'pure-react-carousel'
🧐
```suggestion
import {
  CarouselProvider,
  Slider,
  Slide,
  ButtonBack,
  ButtonNext,
  DotGroup,
} from 'pure-react-carousel'
```

2021-02-20 19:09 UTC, kimvcp approved these changes

2021-02-21 17:40 UTC, kimvcp requested changes
Sorry for the late request, I just found a better solution for you to consider.

2021-02-21 17:40 UTC, kimvcp commented on src/components/HomeCategory/Item.tsx
> +        />
I would consider using `Image` component from [next/image](https://nextjs.org/docs/api-reference/next/image) instead.
Read more [here](https://nextjs.org/docs/basic-features/image-optimization)

2021-02-22 18:31 UTC, Kittinske15 commented on src/components/HomeCategory/Item.tsx
> +const HomeCategoryItem = ({imagePath, alternate, caption}: HomeCategoryItem) => {
Need spacing
```suggestion
const HomeCategoryItem = ({ imagePath, alternate, caption }: HomeCategoryItem) => {
```

2021-02-22 19:23 UTC, kimvcp commented on src/components/HomeCategory/Item.tsx
> +        />
According to this [issue](https://github.com/vercel/next.js/discussions/18739), there are still problems that Next `Image` can't fit its container. Thus, we can use normal `<img/>` for now until the issue is fixed.

2021-02-22 19:27 UTC, Kittinske15 approved these changes

2021-02-22 19:48 UTC, kimvcp approved these changes

2021-02-22 19:49 UTC, merged