[ch117] As a user, I can see brand logo in navigation bar
Cobda/cobda-web pull request #29
Opened 2021-02-22 15:24 UTC by Kittinske15

https://app.clubhouse.io/cobda/story/117/as-a-user-i-can-see-brand-logo-in-navigation-bar

## Why?

In navigation bar, brand logo located at the left side with beautiful design.

## Changes

- Design brand logo
- Brand logo links to its path
- Mobile responsive

## Screenshot(s)

**Before**

**After**
![image](https://user-images.githubusercontent.com/32285869/108729022-b0e26480-755c-11eb-8f56-9246084ea891.png)

2021-02-22 15:49 UTC, LilBank requested changes

2021-02-22 15:49 UTC, LilBank commented on src/styles/layouts/_layout-account.scss
> +    grid-template-rows: map-get($header-height, 'sm') 1fr map-get($footer-height, 'xl');
```suggestion
    grid-template-rows: map-get($header-height, 'xl') 1fr map-get($footer-height, 'xl');
```

2021-02-22 15:49 UTC, LilBank commented on src/styles/layouts/_layout-home.scss
> +    grid-template-rows: map-get($header-height, 'xl') 1fr map-get($footer-height, 'sm');
```suggestion
    grid-template-rows: map-get($header-height, 'xl') 1fr map-get($footer-height, 'xl');
```

2021-02-22 15:52 UTC, kimvcp commented on src/styles/components/_navbar.scss
> +    font-style: normal;
Actually, we don't need these properties since `normal` is their default value.

2021-02-22 15:54 UTC, kimvcp commented on src/styles/abstracts/_variables.scss
> +  xl: 120px,
Please use `rem` instead

2021-02-23 07:11 UTC, LilBank approved these changes

2021-02-23 07:13 UTC, kimvcp approved these changes

2021-02-23 07:15 UTC, merged