[ch121] As a user, I can see locale in navigation bar
Cobda/cobda-web pull request #31
Opened 2021-02-22 21:28 UTC by kimvcp

https://app.clubhouse.io/cobda/story/121/as-a-user-i-can-see-locale-in-navigation-bar

## Why?

This **PR** is for adding dropdown button for `Locale`. It is located at the right of the navigation bar. 

## Changes

- Locale is now a dropdown button.
- Dropdown menu has 2 languages (EN, TH)
- Add Flag images in **SVG** format. 

## Screenshot(s)

**Before**

![Screen Shot 2564-02-23 at 04 24 27](https://user-images.githubusercontent.com/32285706/108772108-2b2bdc80-758f-11eb-935b-df4c8ac9336c.png)
 
**After**

Close menu
![Screen Shot 2564-02-23 at 04 23 38](https://user-images.githubusercontent.com/32285706/108772117-2d8e3680-758f-11eb-9684-e8a54893ca9d.png)

Open menu
![Screen Shot 2564-02-23 at 04 26 17](https://user-images.githubusercontent.com/32285706/108772215-4c8cc880-758f-11eb-9fc3-493c0d3026fe.png)

2021-02-23 13:43 UTC, LilBank requested changes

2021-02-23 13:43 UTC, LilBank commented on public/icons/thailand.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Please optimize and reformat these `.svg` files. Using this: https://jakearchibald.github.io/svgomg/

2021-02-23 13:43 UTC, LilBank commented on public/icons/united-states.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Do we need this flag? Saw no this in any of your usage.

2021-02-23 13:43 UTC, LilBank commented on src/components/LanguageItem/index.tsx
> +}
How about using `enum`? See [here](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums)

2021-02-23 13:43 UTC, LilBank commented on src/components/LanguageItem/index.tsx
> +    return locale === 'th' ? (
Please avoid using magic values.

```suggestion
    return locale === THAI_LOCALE_CODE ? (
```

2021-02-23 13:43 UTC, LilBank commented on src/components/Navbar/Language.tsx
> +  const [selectedLocale, setSelectedLocale] = useState<string>('en')
```suggestion
  const [selectedLocale, setSelectedLocale] = useState<string>(SOME_CONST_HERE)
```

2021-02-23 13:43 UTC, LilBank commented on src/components/Navbar/Language.tsx
> +  }
You can just go for one line statement. And since you shortened the word **previous**, you can go for just **state**.
```suggestion
  const handleDropdownToggle = () => setMenuOpen((state) => !state)
```

2021-02-23 13:43 UTC, LilBank commented on src/components/Navbar/Language.tsx
> +    const isClickedOutside: boolean = !flagRef.current?.contains(event.target as Node)
How about naming the variable as an `event` name?
```suggestion
    const isFocused: boolean = !flagRef.current?.contains(event.target as Node)
```

2021-02-23 13:43 UTC, LilBank commented on src/components/Navbar/Language.tsx
> +    return selectedLocale === 'th' ? (
Avoid magic values here too.

2021-02-23 13:43 UTC, LilBank commented on src/styles/abstracts/_variables.scss
> +$porcelain: #F0F4F5;
```suggestion
$porcelain: #f0f4f5;
```

2021-02-23 13:43 UTC, LilBank commented on src/styles/abstracts/_variables.scss
> +$dropdown-list-shadow : rgb(0 0 0 / 20%);
```suggestion
$dropdown-list-shadow : rgba(0, 0, 0, 0.2);
```

2021-02-23 13:46 UTC, LilBank requested changes

2021-02-23 13:46 UTC, LilBank commented on src/styles/components/_dropdown.scss
> +  &__menu-item {
The corner is pointing out 😅
![Uploading Screen Shot 2564-02-23 at 20.44.15.png…]()

2021-02-23 13:46 UTC, LilBank commented on src/styles/components/_dropdown.scss
> +    margin: rem(16px) 0 0;
<img width="545" alt="Screen Shot 2564-02-23 at 19 23 13" src="https://user-images.githubusercontent.com/32289827/108852454-36771a80-7618-11eb-9e92-2b8a65478307.png">
Unused `margin-bottom`

2021-02-24 08:15 UTC, LilBank approved these changes

2021-02-24 08:18 UTC, Kittinske15 approved these changes

2021-02-24 08:19 UTC, merged