[ch113] As a user, I can see menu list in navigation bar
Cobda/cobda-web pull request #32
Opened 2021-02-23 12:39 UTC by Kittinske15

https://app.clubhouse.io/cobda/story/113/as-a-user-i-can-see-menu-list-in-navigation-bar

## Why?

In navigation bar, menu list is located at the centre. It consists of home, product and about us as a menu items. Which each item has a highlight active while clicking.

## Changes

- Each menu item links to its path.
- Highlight on active for each menu item.

## Screenshot(s)

**Before**
![image](https://user-images.githubusercontent.com/32285869/108844216-67eae880-760e-11eb-857b-2ecfde431b48.png)

**After**

2021-02-24 14:35 UTC, LilBank requested changes

2021-02-24 14:35 UTC, LilBank commented on src/styles/components/_navbar.scss
> +    }
```suggestion
  @include respond-above('md') {
      display: block;
      color: $tornado;
    }

    &:after {
      content: '';
      display: block;
      width: 0;
      transition: width 0.3s;
      color: $dark;
    }

    &:hover::after {
      margin: 0 auto;
      width: 64%;
      transition: width 0.3s;
      border-bottom: rem(3px) solid $havelock-blue;
    }

    &--selected {
      color: $dark;

      &:after {
        content: '';
        display: block;
        width: 64%;
        border-bottom: rem(3px) solid $havelock-blue;
        margin: 0 auto;
      }
    }
  }
```

2021-02-24 14:35 UTC, LilBank commented on src/components/Navbar/Menu.tsx
> +  return <ul className="navbar__menu">{menuItems}</ul>
Should return empty fragments when the route path is empty.

2021-02-24 14:35 UTC, LilBank commented on locales/en/common.json
> +  "aboutUs" : "About us"
```suggestion
  "aboutUs" : "About Us"
```

2021-02-25 16:44 UTC, LilBank approved these changes

2021-02-25 17:08 UTC, Raksani approved these changes

2021-02-25 17:12 UTC, kimvcp approved these changes

2021-02-25 17:13 UTC, merged