[ch220][ch221][ch270] Add prisma, next-auth, and sqlite3
Cobda/cobda-web pull request #57
Opened 2021-04-22 09:56 UTC by LilBank

[STORY_LINK]

## Why?

To describe the reason for creating this **PR**.

## Changes

What are the changes. Explain them explicitly.

## Screenshot(s)

A screenshot **before** the implementation and **after** the implementation.

2021-04-23 15:35 UTC, kimvcp requested changes

2021-04-23 15:35 UTC, kimvcp commented on src/components/SignInForm/Form.tsx
> +  }
Should we use Prettier formatter on this?

```suggestion
    signIn('credentials', {
      email: email,
      password: password,
      callbackUrl: '/'
    })
  }
```

2021-04-23 15:35 UTC, kimvcp commented on src/pages/api/auth/[...nextauth].ts
> +        return !user.code && user.length ? user[0] : new Error('The email or password is incorrect.')
Do you think this variable will make your code more legible for other members?

```suggestion
        const isUserAuthorized = !user.code && user.length

        return isUserAuthorized ? user[0] : new Error('The email or password is incorrect.')
```

2021-04-23 15:35 UTC, kimvcp commented on src/pages/api/auth/[...nextauth].ts
> +  providers : [
```suggestion
  providers: [
```

2021-04-23 15:35 UTC, kimvcp commented on src/prisma/schema.prisma
> +  firstName  String?
```suggestion
  id Int @id @default(autoincrement())
  email String @unique
  password String
  firstName String?
```

2021-04-23 16:07 UTC, LilBank commented on src/prisma/schema.prisma
> +  firstName  String?
Good catch!

2021-04-24 08:32 UTC, kimvcp approved these changes

2021-04-24 13:19 UTC, Kittinske15 approved these changes

2021-04-26 09:16 UTC, Kittinske15 commented on src/prisma/schema.prisma
> +  ownerId Int?
Follow the ``product-registration``, It should contains color, category and delivery option
```suggestion
  id Int @id @default(autoincrement())
  name String
  color String
  size Float
  description String?
  price Int
  owner User? @relation(fields: [ownerId], references: [id])
  ownerId Int?
  category String
  deliveryOption String
```

2021-04-27 14:02 UTC, merged